# Generated by Django 5.1.4 on 2025-02-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
