# Generated by Django 5.1.4 on 2025-02-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_seller_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='id',
        ),
        migrations.AddField(
            model_name='seller',
            name='seller_id',
            field=models.CharField(default='DEFAULT_ID', max_length=10, primary_key=True, serialize=False),
        ),
    ]
