# Generated by Django 5.1.4 on 2025-02-02 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_seller_id_seller_seller_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254, unique=True)),
                ('customer_phone', models.CharField(max_length=15)),
                ('customer_address', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='product_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='product_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='seller_id',
            field=models.ForeignKey(default='DEFAULT_ID', on_delete=django.db.models.deletion.CASCADE, to='app.seller'),
        ),
    ]
